src/Entity/Dog.php
<?php

namespace App\Entity;

use App\Repository\DogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=DogRepository::class)
 */
class Dog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"get_dogs_collection", "get_members_collection", "get_item", "get_dog_item", "get_connected_member"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Groups({"get_dogs_collection", "get_members_collection", "get_hobbies_collection", "get_pictures_collection", "get_item" , "get_dog_item", "get_connected_member"}) 
     */
    private $name;

    /**
     * @ORM\Column(type="integer", length=2)
     * @Assert\NotBlank
     * @Groups({"get_dogs_collection", "get_members_collection", "get_item" , "get_dog_item", "get_connected_member"})
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=35)
     * @Assert\NotBlank
     * @Groups({"get_dogs_collection", "get_members_collection", "get_item", "get_dog_item", "get_connected_member"})
     */
    private $race;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"get_dogs_collection", "get_members_collection", "get_item", "get_dog_item", "get_connected_member"})
     */
    private $presentation;

    /**
     * @ORM\ManyToOne(targetEntity=Member::class, inversedBy="dogs", cascade={"persist"})
     * @Groups({"get_dogs_collection"})
     */
    private $member;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="dog", cascade={"remove"})
     * @Groups({"get_connected_member", "get_dogs_collection"})
     */
    private $pictures;

    /**
     * @ORM\OneToMany(targetEntity=Hobby::class, mappedBy="dog", cascade={"remove"})
     * @Groups({"get_connected_member", "get_dogs_collection"})
     */
    private $hobbies;

    /**
     * @ORM\Column(type="string", length=65, nullable=true)
     * @Groups({"get_dogs_collection", "get_members_collection", "get_connected_member"})
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Groups({"get_dogs_collection", "get_members_collection", "get_connected_member", "get_item" })
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank
     * @Groups({"get_dogs_collection", "get_members_collection", "get_connected_member", "get_item"})
     */
    private $personality;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"get_dogs_collection", "get_members_collection", "get_item" , "get_dog_item", "get_connected_member"}) 
     */
    private $main_picture;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->hobbies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getRace(): ?string
    {
        return $this->race;
    }

    public function setRace(string $race): self
    {
        $this->race = $race;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    /**
     * @return Collection<int, picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setDog($this);
        }

        return $this;
    }

    public function removePicture(picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getDog() === $this) {
                $picture->setDog(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, hobby>
     */
    public function getHobbies(): Collection
    {
        return $this->hobbies;
    }

    public function addHobby(hobby $hobby): self
    {
        if (!$this->hobbies->contains($hobby)) {
            $this->hobbies[] = $hobby;
            $hobby->setDog($this);
        }

        return $this;
    }

    public function removeHobby(hobby $hobby): self
    {
        if ($this->hobbies->removeElement($hobby)) {
            // set the owning side to null (unless already changed)
            if ($hobby->getDog() === $this) {
                $hobby->setDog(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getPersonality(): ?string
    {
        return $this->personality;
    }

    public function setPersonality(string $personality): self
    {
        $this->personality = $personality;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->main_picture;
    }

    public function setMainPicture(string $main_picture): self
    {
        $this->main_picture = $main_picture;

        return $this;
    }
}

src/Controller/Back/DogController.php
<?php

namespace App\Controller\Back;

use App\Entity\Dog;
use App\Entity\Hobby;
use App\Form\DogType;
use App\Repository\DogRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("/back/dog")
 */
class DogController extends AbstractController
{
    /**
     * Route to display all dogs
     * 
     * @Route("/", name="app_back_dog_index", methods={"GET"})
     */
    public function index(DogRepository $dogRepository): Response
    {
        //returning a render as a 'twig view'
        return $this->render('back/dog/index.html.twig', [

            //finding all dogs
            'dogs' => $dogRepository->findAll(),

        ]);
    }

// ---------------- END OF METHOD ---------------------

    /**
     * Route to create a new dog entity
     * 
     * @Route("/new", name="app_back_dog_new", methods={"GET", "POST"})
     */
    public function new(Request $request, DogRepository $dogRepository, SluggerInterface $slugger): Response
    {
        //creating the entity via the form 
        $dog = new Dog();
        $form = $this->createForm(DogType::class, $dog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            //setting the slug thanks to the dog's name (and lowering it)
            $dog->setSlug($slugger->slug($dog->getName())->lower());
            
    // ---------------- MANAGING THE FILE UPLOAD ---------------------

    //@see https://symfony.com/doc/5.4/controller/upload_file.html
    /** @var UploadedFile $pictureFile */
    $pictureFile = $form->get('main_picture')->getData();

            // this condition is needed because the 'picture' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($pictureFile) {
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();    

                // Move the file to the directory where pictures are stored
                try {
                    $pictureFile->move(
                        $this->getParameter('pictures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                    throw $e;
                }

                // updates the 'pictureFilename' property to store the JPG file name
                // instead of its contents
                $dog->setMainPicture($newFilename);
            }

            // ... persist the $member variable or any other work

    // ---------------- END OF MANAGING THE FILE UPLOAD ---------------------
            
            //saving the entity
            $dogRepository->add($dog, true);          

            //redirection route
            return $this->redirectToRoute('app_back_dog_index', [], Response::HTTP_SEE_OTHER);
        }

        // returning a render as a 'twig form'
        return $this->renderForm('back/dog/new.html.twig', [
            'dog' => $dog,
            'form' => $form,
        ]);
    }

// ---------------- END OF METHOD ---------------------    

    /**
     * Route to display a given dog
     * 
     * @Route("/{id}", name="app_back_dog_show", methods={"GET"})
     */
    public function show(Dog $dog): Response
    {
        // returning a render as a 'twig view'
        return $this->render('back/dog/show.html.twig', [
            'dog' => $dog,
        ]);
    }

// ---------------- END OF METHOD ---------------------    

    /**
     * Route to edit a dog entity
     * 
     * @Route("/{id}/edit", name="app_back_dog_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Dog $dog, DogRepository $dogRepository, SluggerInterface $slugger): Response
    {
        //retrieving the entity via the form 
        $form = $this->createForm(DogType::class, $dog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

    // ---------------- MANAGING THE FILE UPLOAD ---------------------

    /** @var UploadedFile $pictureFile */
    $pictureFile = $form->get('main_picture')->getData();

            // this condition is needed because the 'picture' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($pictureFile) {
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();    

                // Move the file to the directory where pictures are stored
                try {
                    $pictureFile->move(
                        $this->getParameter('pictures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                    throw $e;
                }

                // updates the 'pictureFilename' property to store the JPG file name
                // instead of its contents
                $dog->setMainPicture($newFilename);
            }

            // ... persist the $member variable or any other work

    // ---------------- END OF MANAGING THE FILE UPLOAD ---------------------
            
            //setting the slug thanks to the dog 
            $dog->setSlug($slugger->slug($dog->getName())->lower());

            //saving the entity
            $dogRepository->add($dog, true);

            //redirection route
            return $this->redirectToRoute('app_back_dog_index', [], Response::HTTP_SEE_OTHER);
        }

        // returning a render as a 'twig form'
        return $this->renderForm('back/dog/edit.html.twig', [
            'dog' => $dog,
            'form' => $form,
        ]);
    }

// ---------------- END OF METHOD ---------------------   

    /**
     * Route to delete a dog entity
     * 
     * @Route("/{id}", name="app_back_dog_delete", methods={"POST"})
     */
    public function delete(Request $request, Dog $dog, DogRepository $dogRepository): Response
    {
        //making sure to get the token
        if ($this->isCsrfTokenValid('delete'.$dog->getId(), $request->request->get('_token'))) {

            //deleting the entity
            $dogRepository->remove($dog, true);
        }

        //redirection route
        return $this->redirectToRoute('app_back_dog_index', [], Response::HTTP_SEE_OTHER);
    }

// ---------------- END OF METHOD ---------------------   

}

src/Controller/Back/MainController.php
<?php

namespace App\Controller\Back;

use App\Entity\Member;
use App\Repository\DogRepository;
use App\Repository\MemberRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * Route to display the home page for the backoffice 
     * 
     * @Route("/back/", name="app_back")
     */
    public function index(): Response
    { 
        //getting the connected member
        /** @var \App\Entity\Member $member*/
        $member = $this->getUser();

        //returning a render as a 'twig view'
        return $this->render('back/main/backoffice.html.twig', [
            'member' => $member,
        
        ]);
    }

// ---------------- END OF METHOD ---------------------   

    /**
     * Route to display the main page for the backoffice
     * 
     * @Route("/back/main", name="app_main_back")
     */
    public function main(MemberRepository $memberRepository, DogRepository $dogRepository): Response
    {
        //returning a render as a 'twig view'
        return $this->render('back/main/index.html.twig', [
            //finding all members
            'members' => $memberRepository->findAll(),

            //finding all dogs
            'dogs' => $dogRepository->findAll(),
        ]);
    }

// ---------------- END OF METHOD ---------------------   

}

templates/back/dog/_delete_form.html.twig
<form method="post" action="{{ path('app_back_dog_delete', {'id': dog.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer ce chien ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dog.id) }}">
    <button class="btn btn-danger m-1 mx-0">Supprimer</button>
</form>

templates/back/dog/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

    {{ form_widget(form) }}

    <button class="btn btn-success m-0">{{ button_label|default('Valider') }}</button>

{{ form_end(form) }}

templates/back/dog/edit.html.twig
{% extends 'back/base_back.html.twig' %}

{% block title %}Editer le chien{% endblock %}

{% block body %}
    <h1>Editer le chien</h1>

    {{ include('back/dog/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a class="btn btn-warning float-end" href="{{ path('app_back_dog_index') }}">Retour à la liste</a>

    {{ include('back/dog/_delete_form.html.twig') }}
{% endblock %}

templates/back/dog/index.html.twig
{% extends 'back/base_back.html.twig' %}

{% block title %}Listes des chiens{% endblock %}

{% block body %}
    <h1>Listes des chiens</h1><br>

    <table class="table table-hover ">
        <thead class="table-warning">
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Age</th>
                <th>Race</th>
                <th>Présentation</th>
                <th>Propriétaire</th>
                <th>Hobbys</th>
                <th>Photo</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dog in dogs %}
            <tr>
                <td>{{ dog.id }}</td>
                <td>{{ dog.name }}</td>
                <td>{{ dog.age }} ans</td>
                <td>{{ dog.race }}</td>
                <td>{{ dog.presentation }}</td>
                <td><a class="btn btn-sm btn-info" href="{{ path('app_back_member_show', {'id': dog.member.id}) }}">{{ dog.member.username }}</a> </td>
                <td>
                {% for hobby in dog.hobbies %}
                    <ul>
                        <li> {{ hobby }}</li>
                    </ul>
                {% endfor %}
                 <a class="btn btn-sm btn-success" href="{{ path('app_back_hobby_indexhobbies', {'id': dog.id}) }}">Editer les hobbies</a>
                </td>                

                <td>
                    {% for picture in dog.pictures %}
                        <img src="{{ app.request.getBaseURL() }}/assets/uploads/pictures/{{ picture.picture }}" width="100px"><br><br>
                        
                    {% endfor %}
                    <a class="btn btn-sm btn-primary" href="{{ path('app_back_picture_indexpictures', {'id': dog.id}) }}">Editer les photos</a>
                    </td> 
                <td>
                    <a class="btn btn-sm btn-info" href="{{ path('app_back_dog_show', {'id': dog.id}) }}">Voir le profil</a><br>
                    <a class="btn btn-sm btn-secondary my-1" href="{{ path('app_back_dog_edit', {'id': dog.id}) }}">Editer le profil</a><br>
                    {{ include('back/dog/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Pas de chiens enregistrés</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-warning" href="{{ path('app_back_dog_new') }}">Ajouter un nouveau chien</a>
{% endblock %}

templates/back/dog/new.html.twig
{% extends 'back/base_back.html.twig' %}

{% block title %}Nouveau chien{% endblock %}

{% block body %}
    <h1>Création d'un nouveau chien</h1>

    {{ include('back/dog/_form.html.twig') }}

    <a class="btn btn-warning float-end" href="{{ path('app_back_member_index') }}">Retour à la liste</a>
{% endblock %}

templates/back/dog/show.html.twig
{% extends 'back/base_back.html.twig' %}

{% block title %}Fiche de {{ dog.name }}{% endblock %}

{% block body %}
    <h1>Fiche de {{ dog.name }}</h1><br>

    <h3>Profil général</h3>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ dog.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ dog.name }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ dog.age }} ans</td>
            </tr>
            <tr>
                <th>Race</th>
                <td>{{ dog.race }}</td>
            </tr>
            <tr>
                <th>Présentation</th>
                <td>{{ dog.presentation }}</td>
            </tr>
            <tr>
                <th>Propriétaire</th>
                <td><a class="btn btn-info" href="{{ path('app_back_member_show', {'id': dog.member.id}) }}">{{ dog.member.username }}</a></td>
            </tr>
                <th>Taille</th>
                <td>{{ dog.size }}</td>
            </tr>
            <tr>
                <th>Caractère</th>
                <td>{{ dog.personality }}</td>
            </tr>
            <tr>    
                <th>Photo de profil</th>
                <td><img src="{{ app.request.getBaseURL() }}/assets/uploads/pictures/{{ dog.mainPicture }}" width="200px"></td>
            </tr>               
        </tbody>
    </table>

    <p><a class="btn btn-secondary m-1" href="{{ path('app_back_dog_edit', {'id': dog.id}) }}">Editer le profil général</a></p><br>    

    <h3>Ses hobbies</h3>
    <p>(3 maximum)</p>

    <table class="table">
        <tbody>
            <tr>
                <th>Hobbies</th>
            </tr>

            <tr>
                <td>{% for hobby in dog.hobbies %}
                    <ul>
                        <li> {{ hobby }}</li>
                    </ul>
                {% endfor %}</td>
            </tr>
        </tbody>
    </table>

<p><a class="btn btn-secondary m-1" href="{{ path('app_back_hobby_indexhobbies', {'id': dog.id}) }}">Editer les hobbies</a></p><br>

    <h3>Ses photos</h3>
    <p>(3 maximum)</p>

    <table class="table">
        <tbody>
            <tr>
                <th>Photos</th>
            </tr>

            <tr>
                <td>
                    {% for picture in dog.pictures %}
                        <img src="{{ app.request.getBaseURL() }}/assets/uploads/pictures/{{ picture.picture }}" width="200px">                        
                    {% endfor %}</td>
            </tr>
        </tbody>
    </table>

<p><a class="btn btn-secondary m-1" href="{{ path('app_back_picture_indexpictures', {'id': dog.id}) }}">Editer les photos</a></p>

<p>{{ include('back/dog/_delete_form.html.twig') }}</p><br>

<a class="btn btn-warning float-end" href="{{ path('app_back_member_index') }}">Retour à la liste des membres</a>

<p><a class="btn btn-warning " href="{{ path('app_back_dog_index') }}">Retour à la liste des chiens</a></p>

{% endblock %}